#!/bin/bash

if [ -z $EXP_ID ]; then
    echo "Must set EXP_ID before running"
elif [ -z $1 ]; then
    echo "No argument provided"
elif [ $1 = "batch" ]; then
    rastervision -p batch run aws_batch -x -r -s 10 -e experiment.experiment \
        analyze chip train predict eval bundle POSTPROCESS \
        -a experiment_id $EXP_ID \
        -a root_uri s3://carderne-rv/ \
        -a train_stac_uri s3://drivendata-competition-building-segmentation/train_tier_1/catalog.json \
        -a test_stac_uri /opt/data/test/catalog.json \
        -a train_img_dir s3://carderne-rv/split/ \
        -a test_img_dir s3://drivendata-competition-building-segmentation/test/ \
        -a test_exclude $EXCLUDE
elif [ $1 = "split" ]; then
    rastervision -p batch run aws_batch -x -s 8 -e experiment.split \
        PREPROCESS \
        -a root_uri s3://carderne-rv/ \
        -a train_stac_uri s3://drivendata-competition-building-segmentation/train_tier_1/catalog.json \
        -a split_dir s3://carderne-rv/split/
elif [ $1 = "zip" ]; then
    rastervision -p batch run aws_batch -x -e experiment.zip \
        ZIP \
        -a experiment_id $EXP_ID \
        -a root_uri s3://carderne-rv/ \
        -a test_stac_uri /opt/data/test/catalog.json
elif [ $1 = "test" ]; then
    rastervision -p test run local -x -r -s 2 -e experiment.experiment \
        analyze chip train predict eval bundle \
        -a experiment_id  $EXP_ID \
        -a root_uri /opt/data/scratch/ \
        -a train_stac_uri /opt/data/train_tier_1/catalog.json \
        -a test_stac_uri /opt/data/test/catalog.json \
        -a train_img_dir /opt/data/split/ \
        -a test_img_dir /opt/data/test/ \
        -a test_exclude $EXCLUDE \
        -a test True
elif [ $1 = "noop" ]; then
    rastervision -p batch run aws_batch -x -e experiment.noop \
        NOOP
fi
