#!/bin/bash

ACCOUNT_ID=$(aws sts get-caller-identity --output text --query 'Account' --profile rv)
AWS_REGION="us-east-1"
aws ecr get-login --no-include-email --region ${AWS_REGION} --profile rv | bash;

IMAGE_NAME="raster-vision-pytorch-custom"
ECR_IMAGE="raster-vision-pytorch-custom"
ECR_IMAGE_TAG="latest"

docker tag ${IMAGE_NAME} \
    ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_IMAGE}:${ECR_IMAGE_TAG}
docker push \
    ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_IMAGE}:${ECR_IMAGE_TAG}
