#!/bin/bash

export EXPERIMENT_ID=benchmark1
export ROOT_URI=s3://carderne-rv/
export TRAIN_STAC_URI=s3://drivendata-competition-building-segmentation/train_tier_1/catalog.json
export TRAIN_IMG_DIR=s3://carderne-rv/split/
export TEST_STAC_URI=/opt/data/test/catalog.json
export TEST_IMG_DIR=s3://drivendata-competition-building-segmentation/test/

rastervision run aws_batch -x -r -s 10 -e experiment.experiment \
    chip train predict bundle POSTPROCESS \
    -a experiment_id $EXPERIMENT_ID \
    -a root_uri $ROOT_URI \
    -a train_stac_uri $TRAIN_STAC_URI \
    -a test_stac_uri $TEST_STAC_URI \
    -a train_img_dir $TRAIN_IMG_DIR \
    -a test_img_dir $TEST_IMG_DIR \
