#!/bin/bash

export ROOT_URI=s3://carderne-rv/
export TRAIN_STAC_URI=s3://drivendata-competition-building-segmentation/train_tier_1/catalog.json
export TRAIN_IMG_DIR=s3://carderne-rv/split/

rastervision -p batch run aws_batch -x -s 8 -e experiment.split \
    PREPROCESS \
    -a root_uri $ROOT_URI \
    -a train_stac_uri $TRAIN_STAC_URI \
    -a split_dir $TRAIN_IMG_DIR \
