#!/bin/bash

export EXPERIMENT_ID=benchmark1
export ROOT_URI=s3://carderne-rv/
export TEST_STAC_URI=/opt/data/test/catalog.json

rastervision -p batch run aws_batch -x -e experiment.zip \
    ZIP \
    -a experiment_id $EXPERIMENT_ID \
    -a root_uri $ROOT_URI \
    -a test_stac_uri $TEST_STAC_URI \
